# Generated by Django 6.0 on 2026-09-20 21:23

import UserPanel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopbarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('left', 'Left side'), ('right', 'Right side')], default='left', max_length=5)),
                ('kind', models.CharField(choices=[('text', 'Text (no link)'), ('link', 'Link'), ('divider', 'Divider  |')], default='text', max_length=7)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap Icons class, e.g. bi-truck', max_length=60)),
                ('href', models.CharField(blank=True, max_length=500, validators=[UserPanel.models.validate_href])),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('visible_from', models.CharField(choices=[('always', 'All screens'), ('sm', 'Small screens and up (576px+)'), ('md', 'Tablets and up (768px+)'), ('lg', 'Laptops and up (992px+)')], default='always', max_length=6)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['side', 'order', 'id'],
            },
        ),
    ]
