# Generated by Django 6.0 on 2026-02-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Payment Failed')], default='pending', max_length=20),
        ),
    ]
