# Generated by Django 6.0 on 2026-03-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_orderrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='Web.orderitem'),
        ),
    ]
