# Generated by Django 6.0 on 2026-03-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0009_notification_notificationrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_dispatched', 'Order Dispatched'), ('order_delivered', 'Order Delivered'), ('order_canceled', 'Order Canceled'), ('order_status', 'Order Status'), ('promotion', 'Promotion / Offer')], max_length=50),
        ),
    ]
