# Generated by Django 6.0 on 2026-08-03 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0015_wishtobuy'),
        ('products', '0035_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishtobuy',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
    ]
