# Generated by Django 6.0 on 2026-09-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0020_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submited', 'Submited'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Cancelled'), ('dispatch', 'Dispatch'), ('ordersuccessfull', 'Order Success Full'), ('failed', 'Payment Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submited', 'Submited'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Cancelled'), ('dispatch', 'Dispatch'), ('ordersuccessfull', 'Order Success Full'), ('failed', 'Payment Failed')], default='pending', max_length=20),
        ),
    ]
