# Generated by Django 6.0 on 2026-09-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('REGISTER', 'Register'), ('LOGIN', 'Login'), ('RESET_PASSWORD', 'Reset Password'), ('ORDER_CONFIRM', 'Order Confirm')], max_length=20),
        ),
    ]
