# Generated by Django 6.0 on 2026-09-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_otp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='block_type',
            field=models.CharField(blank=True, choices=[('temporary', 'Temporary'), ('permanent', 'Permanent')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked_from_ordering',
            field=models.BooleanField(default=False),
        ),
    ]
