# Generated by Django 6.0 on 2026-01-01 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_attribute_attribute_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., RAM Size, Fabric, or Voltage', max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('is_multiple', models.BooleanField(default=False, help_text='Can user select multiple values?')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_attributes', to='products.attribute_types')),
                ('categories', models.ManyToManyField(blank=True, related_name='attributes', to='products.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
                'unique_together': {('name', 'attribute_type')},
            },
        ),
    ]
