# Generated by Django 6.0 on 2026-01-01 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='categories',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='categories',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='products.category'),
        ),
    ]
