# Generated by Django 6.0 on 2026-01-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productattribute_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='categories',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='products.category'),
        ),
    ]
