# Generated by Django 6.0 on 2026-01-02 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('estimated_delivery_time', models.CharField(help_text='e.g. 3-5 Business Days', max_length=50)),
                ('shipping_type', models.CharField(choices=[('flat', 'Flat Rate'), ('weight', 'Weight Based'), ('price', 'Price Based'), ('free', 'Free Shipping')], default='flat', max_length=20)),
                ('base_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_class', models.CharField(choices=[('standard', 'Standard'), ('reduced', 'Reduced'), ('zero', 'Zero Rate')], default='standard', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_methods_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_methods_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. FedEx, DHL', max_length=100)),
                ('provider_code', models.CharField(help_text='Unique identifier', max_length=50, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('api_endpoint', models.URLField(blank=True, max_length=255, null=True)),
                ('has_standard_delivery', models.BooleanField(default=True)),
                ('has_express_delivery', models.BooleanField(default=False)),
                ('has_overnight_delivery', models.BooleanField(default=False)),
                ('rate_type', models.CharField(choices=[('api', 'Fetch from API'), ('flat', 'Flat Rate'), ('zone', 'Zone Based')], default='api', max_length=10)),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Optional markup %', max_digits=5)),
                ('min_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('enable_tracking', models.BooleanField(default=True)),
                ('auto_generate_label', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipping Provider',
                'verbose_name_plural': 'Shipping Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Domestic Zone', max_length=150, unique=True)),
                ('country', models.CharField(help_text='e.g. USA, UK', max_length=100)),
                ('state_region', models.CharField(blank=True, help_text='Optional State or Province', max_length=100, null=True)),
                ('zip_codes', models.TextField(blank=True, help_text='Comma separated list of postal codes', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_modified', to=settings.AUTH_USER_MODEL)),
                ('shipping_methods', models.ManyToManyField(blank=True, related_name='zones', to='products.shippingmethod', verbose_name='Shipping Methods')),
                ('shipping_providers', models.ManyToManyField(blank=True, related_name='zones', to='products.shippingprovider', verbose_name='Shipping Providers')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('order_value', 'Order Value'), ('order_weight', 'Order Weight'), ('item_count', 'Item Count')], default='order_value', max_length=20)),
                ('min_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Min Order Value/Weight', max_digits=12)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, help_text='Max Order Value/Weight', max_digits=12, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_modified', to=settings.AUTH_USER_MODEL)),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.shippingmethod')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='products.shippingzone')),
            ],
        ),
    ]
