# Generated by Django 6.0 on 2026-01-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_productimage_productreview_productvariant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='discounted_price',
            field=models.PositiveIntegerField(blank=True, help_text='Enter discounted price', null=True),
        ),
    ]
