# Generated by Django 6.0 on 2026-01-05 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_stock_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount'), ('buy_x_get_y', 'Buy X Get Y'), ('free_delivery', 'Free Delivery')], default='percentage', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductVariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('option_name', models.CharField(help_text='e.g. Color, Size', max_length=100)),
                ('option', models.CharField(help_text='Comma separated values e.g. Red,Blue,Green', max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_options', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
