# Generated by Django 6.0 on 2026-01-05 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_promotion_discount_type_productvariantoption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='compare_at_price',
            field=models.PositiveIntegerField(blank=True, help_text='Enter compare at price', null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter percentage or flat amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
