# Generated by Django 6.0 on 2026-01-06 07:29

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_promotion_compare_at_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/', validators=[products.models.Product.validate_video_size]),
        ),
    ]
