# Generated by Django 6.0 on 2026-01-25 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_shipping_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='admin_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_customer_reviews',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_for_preorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='available_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='disable_buy_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='disable_wishlist_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='mark_as_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='other_product_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('1', 'Simple'), ('2', 'Grouped')], default='simple', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='ship_separately',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='show_on_home_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='visible_individually',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tax_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.taxcategory'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_method', models.CharField(choices=[('dont_track', 'Don’t Track Inventory'), ('track', 'Track Inventory'), ('track_by_attributes', 'Track By Product Attributes')], default='dont_track', max_length=30)),
                ('min_cart_qty', models.PositiveIntegerField(default=1)),
                ('max_cart_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('allowed_quantities', models.CharField(blank=True, help_text='Example: 1,2,5,10', max_length=255)),
                ('not_returnable', models.BooleanField(default=False)),
                ('product_availability_range', models.CharField(blank=True, max_length=100)),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('low_stock_quantity', models.IntegerField(blank=True, null=True)),
                ('backorders', models.CharField(choices=[('no_backorder', 'No Backorder'), ('allow_below_0', 'Allow Qty Below 0'), ('allow_below_0_notify', 'Allow Below 0 And Notify Customer')], default='no_backorder', max_length=30)),
                ('multiple_warehouses', models.BooleanField(default=False)),
                ('display_availability', models.BooleanField(default=True)),
                ('display_stock_quantity', models.BooleanField(default=False)),
                ('minimum_stock_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('low_stock_activity', models.CharField(choices=[('nothing', 'Nothing'), ('disable_buy', 'Disable Buy Button'), ('unpublish', 'Unpublish Product')], default='nothing', max_length=20)),
                ('notify_qty_below', models.PositiveIntegerField(blank=True, null=True)),
                ('allow_back_in_stock_subscriptions', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.warehouse')),
            ],
        ),
    ]
