# Generated by Django 6.0 on 2026-02-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_additional_shipping_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
