# Generated by Django 6.0 on 2026-02-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_productimage_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='star_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
