# Generated by Django 6.0 on 2026-02-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_rating_count_product_star_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qoute',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
