# Generated by Django 6.0 on 2026-04-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/mobile/'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='web_image',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/web/'),
        ),
    ]
