# Generated by Django 6.0 on 2026-04-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_promotion_mobile_image_promotion_web_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='show_on_home',
            field=models.BooleanField(default=True),
        ),
    ]
