# Generated by Django 6.0 on 2026-04-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_promotion_show_on_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/banner/'),
        ),
    ]
