# Generated by Django 6.0 on 2026-04-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_promotion_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productvariantoption',
            name='is_custom_ui',
            field=models.BooleanField(default=False),
        ),
    ]
