# Generated by Django 6.0 on 2026-05-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_productvariant_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='value',
        ),
        migrations.AddField(
            model_name='productvariantoption',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
