# Generated by Django 6.0 on 2026-09-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_productquestion_read_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage (%)')], default='percentage', max_length=20),
        ),
    ]
