# Generated by Django 6.0 on 2026-09-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_promotion_discount_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'Picture', 'verbose_name_plural': 'Pictures'},
        ),
        migrations.AddField(
            model_name='picture',
            name='button_link',
            field=models.CharField(blank=True, help_text='URL or path, e.g. /shop/', max_length=255, null=True, verbose_name='Button Link'),
        ),
        migrations.AddField(
            model_name='picture',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='picture',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Eyebrow (small text above title)'),
        ),
        migrations.AddField(
            model_name='picture',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers show first', verbose_name='Sort Order'),
        ),
    ]
